# Deploy to Firebase Hosting staging channel when merged to staging branch

name: Deploy to Firebase Hosting on staging merge
on:
  push:
    branches:
      - staging
permissions:
  contents: read
jobs:
  build_and_deploy_staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TARKOVTRACKER_ORG }}
          channelId: staging
          projectId: tarkovtracker-org
