name: Close stale issues and PRs
on:
  schedule:
    - cron: '17 3 * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write
  contents: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v10
        with:
          repo-token: ${{ github.token }}

          days-before-issue-stale: 45
          days-before-pr-stale: 21
          days-before-issue-close: 14
          days-before-pr-close: 14

          stale-issue-message: >
            This issue is stale due to inactivity. It will close in 14 days unless there’s new activity.
          stale-pr-message: >
            This PR is stale due to inactivity. It will close in 14 days unless there’s new activity.

          stale-issue-label: 'status:stale'
          stale-pr-label: 'status:stale'
          close-issue-label: 'status:auto-closed'
          close-pr-label: 'status:auto-closed'

          exempt-issue-labels: 'status:never-stale,security,pinned'
          exempt-pr-labels: 'status:never-stale,security'
          exempt-all-milestones: true
          remove-stale-when-updated: true
          delete-branch: true
          operations-per-run: 500
